### ISSUE TITLE
Crash error on select "Employ Now" button [EP 1.0.3][BepInEx 5.4.16][TbAPI 0.1.0][Tb 20211202-10685be-sw]

### ISSUE THREAD

**Issue by Slaymeister** [mhgar/EmploymentPriority#1]
Crash error when selecting "Employ Now" with Dec 12 release of the game. 

Error: MissingMethodException: Method not found: System.Collections.Generic.IEnumerable`1<!!0> Timberborn.GameDistricts.DistrictPopulation.GetEnabledCharacters<!0>()

Link to error report with repro files.  https://1drv.ms/u/s!Aj3i3s_bJkfxnaEum5c8iNUckwlJqw?e=V7Ibu0
Repro files:
Pre-Crash 2021-12-13 12h55m, Day 9-12.timber - save game from right before the crash. Crashes consistently
mods.yaml - Thunderstore Mod Manager profile of all installed mods (8)

Repro: Load save game with mods. Select Hauling Building, click "Employ Now".  Fatality.

Mods list:
  name: BepInEx-BepInExPack_Timberborn
  name: Mo-UndesireableStorage
  name: Timberborn_Central-TimberAPI
  name: Hectare-EmploymentPriority
  name: Elec-ExtendedArchitecture
  name: hawkfalcon-UnifiedFactions
  name: PB_Ozai-District_Extender
  name: Nobody-FloodGatesMult

**Comment by mhgar** [comment]
Hi, thanks for the detailed report. I'll try get this fixed very soon.

**Comment by mhgar** [comment]
Hey again. Are you on the experimental branch of the game? There were some breaking changes between main and experimental which has been fixed in the mod. If you are on the main branch of the game I recommend using version 1.0.1 of the mod.

**Comment by mhgar** [comment]
Hi again. I'm closing this issue now as the experimental stuff is back on the main branch of the game.
